### ISSUE TITLE
Decrease ram usage and improve checking

### ISSUE THREAD

**Issue by bwfcwalshyPluginDev** [bwfcwalshyPluginDev/JarChecker#10]
For the extra checks we have booleans setOp, hardCodedName and opMe now while these take little ram considering they are 1 bit each (3 total) but this can be decreased to 0 and also improve the checking. So instead of using the booleans we can just check if the checks have been found and do the actions, and to improve the check so it may not falsely fire if they are in different classes make it check if they are in the same class. 

// I can work on this tomorrow ~ 1pm if anyone wants to implement this before then please assign and say so. I am fine doing it tomorrow though so no need to go out your way.

**Comment by ArsenArsen** [comment]
Addressed in https://github.com/bwfcwalshyPluginDev/JarChecker/commit/9c81f95b725b17454c4f26c042d9036d23ec260c
