### ISSUE TITLE
Indentation not happening in methods?

### ISSUE THREAD

**Issue by bwfcwalshyPluginDev** [bwfcwalshyPluginDev/JarChecker#15]
I pulled the latest code today and all the indentation in a method has gone, by that I don't mean nothing is indented I just mean it seems to ignore the indentation of the method

Example:
```java
public void a(){  
System.out.println("Not indented");  
}
```

Whereas the way I code and the way everyone else I know codes
```java
public void a(){
    System.out.println("Indented");
}
```

Not sure who is ignoring the method but it seems strange to me.

**Comment by ArsenArsen** [comment]
https://github.com/fesh0r/fernflower
Look at the instructions in README

**Comment by bwfcwalshyPluginDev** [comment]
What about it Arsen? This concerns our code, fernflower doesn't mess with our code indentation

**Comment by ArsenArsen** [comment]
Oh.. My thoughts vvere that you saw it decompile that way xD Sorry.

Thats why I added the last section into README.md yesterday

**Comment by ArsenArsen** [comment]
Never mind that commit
[javaformatter.zip](https://github.com/bwfcwalshyPluginDev/JarChecker/files/367925/javaformatter.zip) allows formatter tags but works fine.

**Comment by bwfcwalshyPluginDev** [comment]
Code now has correct formatting and new formatter has been posted. Closed.
