### ISSUE TITLE
Shutdown could throw false positives

### ISSUE THREAD

**Issue by EthanZeigler** [bwfcwalshyPluginDev/JarChecker#20]
I know that some of my plugins have a shutdown method that is invoked by onDisable to some of my other classes. This could cause false positives. I'd check the shutdown method originating from it's main source, the Bukkit class.

**Comment by bwfcwalshyPluginDev** [comment]
True, have actually used this in my plugin in the past. Will address tomorrow.

**Comment by ArsenArsen** [comment]
I have tried ti fix this, please have a test.

**Comment by I-Al-Istannen** [comment]
Me too. Test would be nice ;)
