### ISSUE TITLE
SymbolTree - No such element

### ISSUE THREAD

**Issue by ArsenArsen** [bwfcwalshyPluginDev/JarChecker#24]
So, while decompiling WorldGuard, I got this message:

> Exception in thread "Scan" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.bwfcwalshy.jarchecker.symbol_tables.SymbolTreeParser.parse(SymbolTreeParser.java:89)
	at com.bwfcwalshy.jarchecker.Checker.check(Checker.java:132)
	at com.bwfcwalshy.jarchecker.Main.decompilerStart(Main.java:195)
	at com.bwfcwalshy.jarchecker.gui.MainWindow$10.run(MainWindow.java:218)

First reaction was how lovely, lets fix this, but I was working on something else, and I also have no idea how a symbol tree works.

Anyways, good luck fixing that.

**Comment by I-Al-Istannen** [comment]
@ArsenArsen 
What state? The current master tree?
I can see where this comes from, but it totally amazes me. Could you add a `System.out.println(sourceFile);` right under `this.currentNode = rootNode;` and send me the file in question?

**Comment by ArsenArsen** [comment]
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
C:\Users\Arsen\AppData\Roaming\.JarChecker\WorldGuard-src\WorldGuard.jar
Exception in thread "Scan" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.bwfcwalshy.jarchecker.symbol_tables.SymbolTreeParser.parse(SymbolTreeParser.java:90)
	at com.bwfcwalshy.jarchecker.Checker.check(Checker.java:132)
	at com.bwfcwalshy.jarchecker.Main.decompilerStart(Main.java:195)
	at com.bwfcwalshy.jarchecker.gui.MainWindow$10.run(MainWindow.java:218)

**Comment by I-Al-Istannen** [comment]
@ArsenArsen 
Well, that was not what I expected... Though this variable meant something else. Anyways, do you have a downloadlink for this?

I will be away for a bit, but it would probably help a lot.

Thanks though!

**Comment by ArsenArsen** [comment]
@I-Al-Istannen I just tested with another jar, pops up again. Let me test this without a modification I made earlier, although I do not see why it would affect this

**Comment by ArsenArsen** [comment]
No, same thing

**Comment by I-Al-Istannen** [comment]
@ArsenArsen 
Link? Having the file myself would help :)

**Comment by ArsenArsen** [comment]
Just download the official WorldGuard Jar. Also fires on mcMMO. I think it is about inner classes, When I used a jar without them it was fine. Let me test that theory.

**Comment by ArsenArsen** [comment]
Yea, thats the issue. Inner classes.

**Comment by I-Al-Istannen** [comment]
@ArsenArsen 
Thanks, I will have a look.

**Comment by ArsenArsen** [comment]
@I-Al-Istannen It works fine on my other test subjects, just not those with inner classes.

**Comment by I-Al-Istannen** [comment]
@ArsenArsen 
```
File name: worldguard-6.1.2.jar

File checked with JarChecker v0.8.4 by bwfcwalshy

Found: 
Equals name x2
Url x12
Thread sleep x2
While true x26
Runtime x2
Plugin is malicious!
```

Thank you, it was a logic error in the bracket parsing logic :) Thanks!
Should be fixed now as well as two other critical errors in the parser.

I will make a pull request soon.

**Comment by I-Al-Istannen** [comment]
It is also cool how this parser makes up most of the recent issues :P
Well, I guess I will live with it. Sorry guys ;)

**Comment by ArsenArsen** [comment]
Allright. Thanks mate. Testing.

**Comment by I-Al-Istannen** [comment]
I'm exited :P
