### ISSUE TITLE
Command gets fired for EQUALS_NAME

### ISSUE THREAD

**Issue by bwfcwalshyPluginDev** [bwfcwalshyPluginDev/JarChecker#3]
if(cmd.getName().equalsIgnoreCase("example")){
This would be fired for EQUALS_NAME due to it having the getName().equals... in it.

**Comment by bwfcwalshyPluginDev** [comment]
I will get this sorted shortly.

**Comment by I-Al-Istannen** [comment]
I think I fixed this. At least I couldn't reproduce it now. If you could send me a char with a false or true alert, I would be grateful.
```java
EQUALS_NAME(line -> {
			Pattern pattern = Pattern.compile("getName\\(\\).(equals|equalsIgnoreCase)\\(\\\"[a-zA-Z0-9]+\\\"\\)");
			if(!pattern.matcher(line).find()) {
				return false;
			}
			else {
				Pattern nameOfObjectPattern = Pattern.compile("([^\\s()]+)(?=.getName\\(\\))");
				Matcher matcher = nameOfObjectPattern.matcher(line);
				if(matcher.find()) {
					String name = matcher.group(1);
					Optional<String> type = currentSymbolTree.getFullyQualifiedType(currentLine, name);
					if(type.isPresent()) {
						return type.get().equals("org.bukkit.command");
					}
				}
				else {
					Logger.print("No match! Please check the Parser: " + line);
				}
				return true;
			}
		}, WarningType.WARNING),
```
This requires some other changes I made. No idea how I should pull them, as they rely on a different state (after my pull request) and are therefore not easily mergable with ArsenArsen's changes to the Test branch.

**Comment by ArsenArsen** [comment]
Git uses powerfull strategy called octopus. Lets hope it is powerfull enough to merge that pull request.

**Comment by bwfcwalshyPluginDev** [comment]
God this will be fun to merge. Let's try and get this working in the test branch before pushing out. The test branch is now up to date with master and is ready for the merge of this.

**Comment by ArsenArsen** [comment]
Yea.. How about we just paste the changes into the old files and then push them up?

**Comment by bwfcwalshyPluginDev** [comment]
Still wouldn't make it mergable because it would be too much of a change. We will have to go through file by file and manually merge them.

**Comment by ArsenArsen** [comment]
Thats what I meant. We take these changes and put them in manualy and then push.

**Comment by bwfcwalshyPluginDev** [comment]
Yeah feel free to ask for help but I'm on iPad so it will be slow

**Comment by ArsenArsen** [comment]
It is fixed.
