### ISSUE TITLE
Improve the found

### ISSUE THREAD

**Issue by bwfcwalshyPluginDev** [bwfcwalshyPluginDev/JarChecker#5]
Change multiple of something found to XYZ x #

Example:

**Before**:
Found:
Url
Url

**To**:
Found: 
Url x 2

**Comment by ArsenArsen** [comment]
I will try addressing this issue.

**Comment by ArsenArsen** [comment]
This issue was addressed in JarChecker 0.7 at a pull request [6](https://github.com/bwfcwalshyPluginDev/JarChecker/pull/6)

**Comment by bwfcwalshyPluginDev** [comment]
Was added in PR #6
